# Generated by Django 4.2.4 on 2023-09-29 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Almacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('maximo', models.IntegerField()),
                ('minimo', models.IntegerField()),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Ubicación',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('activo', models.BooleanField(default=False)),
                ('fila', models.IntegerField()),
                ('columna', models.IntegerField()),
                ('pasillo', models.IntegerField()),
                ('cantidad_limite', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('almacen_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistica.almacen')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.produto')),
            ],
        ),
    ]
