# Generated by Django 4.2.4 on 2023-09-29 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('rif', models.CharField(max_length=10)),
                ('telefono', models.CharField(max_length=11)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Unidad_Medida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('simbolo', models.CharField(max_length=3)),
                ('activo', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=25)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('costo', models.FloatField()),
                ('ultimo_cost', models.FloatField()),
                ('activo', models.BooleanField(default=False)),
                ('precio', models.FloatField()),
                ('descripcion', models.TextField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('verduras', 'Verduras'), ('carnes', 'Carnes'), ('pescado_mariscos', 'Pescado y Mariscos'), ('frutas', 'Frutas'), ('lacteos', 'Lácteos y produccions Lácteos')], max_length=50)),
                ('fecha_expiracion', models.DateField()),
                ('estado', models.CharField(choices=[('fresco', 'Fresco'), ('maduro', 'Maduro'), ('en_su_punto', 'En su punto'), ('pasado', 'Pasado'), ('podrido', 'Podrido')], max_length=50)),
                ('uso', models.CharField(choices=[('verduras_ensalada', 'Ensalada de verduras frescas'), ('verduras_salteado', 'Salteado de verduras'), ('verduras_sopa', 'Sopa de verduras'), ('carnes_parrillada', 'Parrillada de carne'), ('carnes_estofado', 'Estofado de carne'), ('carnes_hamburguesa', 'Hamburguesa de carne'), ('pescado_sushi', 'Sushi de pescado fresco'), ('pescado_ceviche', 'Ceviche de pescado y mariscos'), ('pescado_filete', 'Filete de pescado a la parrilla'), ('frutas_batidos', 'Batidos de frutas frescas'), ('frutas_tarta', 'Tarta de frutas'), ('frutas_mermelada', 'Mermelada de frutas'), ('lacteos_macarrones', 'Macarrones con queso'), ('lacteos_helado', 'Helado de leche y crema'), ('lacteos_mantequilla', 'Mantequilla para cocinar y hornear')], max_length=50)),
                ('categoria_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.categoria')),
                ('proveedor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.proveedor')),
                ('unidad_medida_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.unidad_medida')),
            ],
        ),
        migrations.CreateModel(
            name='Menu_Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.menu')),
                ('producto_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.produto')),
            ],
        ),
    ]
