# Generated by Django 4.2.4 on 2023-09-29 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='tipo',
            field=models.CharField(choices=[('ingrediente', 'Ingrediente'), ('platillo ', 'platillo '), ('insumo', 'insumo')], max_length=50),
        ),
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('ingrediente_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingrediente', to='produccion.produto')),
                ('platillo_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platillo', to='produccion.produto')),
            ],
        ),
    ]
